r1:
  image: redis
r2:
  image: redis
r3:
  image: redis
shell:
  build: .
  dockerfile: Dockerfile.shell
  volumes:
    - .:/tmp/
  links:
    - r1
    - r2
    - r3
  command: "ipython -ic \"import redis; import majorityredis ; import logging; logging.basicConfig(); majorityredis.log.setLevel(10); getmr = lambda: majorityredis.MajorityRedis([redis.StrictRedis(host=x) for x in ['r1', 'r2', 'r3']], 3) ; mr = getmr()\""
